import request from "@/utils/request";
const LETTER_TEMPLATE_BASE_URL = "/application/workflow";

// 查询所有工作流状态
export function getWorkflowStatusList(params: any) {
  return request({
    url: `${LETTER_TEMPLATE_BASE_URL}/statusList`,
    method: "get",
    params
  });
  // return {
  //   "code": 200,
  //   "data": [
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-06-04T09:05:06.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-06-04T09:05:06.000+00:00",
  //       "workflowState": 0,
  //       "permissionRole": "applicant",
  //       "externalStatusEng": "Draft",
  //       "externalStatusChi": "暫存",
  //       "externalStatusSchi": "暂存",
  //       "internalStatus": "Draft",
  //       "internalAction": "Issue",
  //       "haveRemark": false,
  //       "haveLetter": true
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:05.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:05.000+00:00",
  //       "workflowState": 1,
  //       "permissionRole": "RO",
  //       "externalStatusEng": "Submitted",
  //       "externalStatusChi": "已遞交",
  //       "externalStatusSchi": "已递交",
  //       "internalStatus": "Submitted",
  //       "internalAction": "Issue",
  //       "haveRemark": false,
  //       "haveLetter": true
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:05.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:05.000+00:00",
  //       "workflowState": 2,
  //       "permissionRole": "RO",
  //       "externalStatusEng": "Submitted",
  //       "externalStatusChi": "已遞交",
  //       "externalStatusSchi": "已递交",
  //       "internalStatus": "Pending Acknowledgement Letter",
  //       "internalAction": "Acknowledge",
  //       "haveRemark": true,
  //       "haveLetter": false
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:05.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:05.000+00:00",
  //       "workflowState": 3,
  //       "permissionRole": "RO",
  //       "externalStatusEng": "Resubmitted",
  //       "externalStatusChi": "已重新遞交",
  //       "externalStatusSchi": "已重新递交",
  //       "internalStatus": "Resubmitted",
  //       "internalAction": "",
  //       "haveRemark": false,
  //       "haveLetter": false
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:05.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:05.000+00:00",
  //       "workflowState": 4,
  //       "permissionRole": "RO",
  //       "externalStatusEng": "Processing",
  //       "externalStatusChi": "處理中",
  //       "externalStatusSchi": "处理中",
  //       "internalStatus": "Pre-vetting",
  //       "internalAction": "Proceed",
  //       "haveRemark": true,
  //       "haveLetter": false
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:05.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:05.000+00:00",
  //       "workflowState": 5,
  //       "permissionRole": "RO,PVO",
  //       "externalStatusEng": "Processing",
  //       "externalStatusChi": "處理中",
  //       "externalStatusSchi": "处理中",
  //       "internalStatus": "Vetting",
  //       "internalAction": "Approve, Reject, Query",
  //       "haveRemark": true,
  //       "haveLetter": false
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:05.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:05.000+00:00",
  //       "workflowState": 6,
  //       "permissionRole": "RO",
  //       "externalStatusEng": "Processing",
  //       "externalStatusChi": "處理中",
  //       "externalStatusSchi": "处理中",
  //       "internalStatus": "Querying (Pending Mail)",
  //       "internalAction": "Proceed",
  //       "haveRemark": false,
  //       "haveLetter": false
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:05.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:05.000+00:00",
  //       "workflowState": 7,
  //       "permissionRole": "VO",
  //       "externalStatusEng": "Processing",
  //       "externalStatusChi": "處理中",
  //       "externalStatusSchi": "处理中",
  //       "internalStatus": "Pending Approval",
  //       "internalAction": "Approve, Reject",
  //       "haveRemark": true,
  //       "haveLetter": false
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:05.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:05.000+00:00",
  //       "workflowState": 8,
  //       "permissionRole": "RO,VO",
  //       "externalStatusEng": "Processing",
  //       "externalStatusChi": "處理中",
  //       "externalStatusSchi": "处理中",
  //       "internalStatus": "Pending Approval Letter",
  //       "internalAction": "Confirm",
  //       "haveRemark": false,
  //       "haveLetter": true
  //     },
  //     {
  //       "deleted": true,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:05.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:05.000+00:00",
  //       "workflowState": 9,
  //       "permissionRole": "VO",
  //       "externalStatusEng": "Processing",
  //       "externalStatusChi": "處理中",
  //       "externalStatusSchi": "处理中",
  //       "internalStatus": "Confirm Approval Letter",
  //       "internalAction": "Queue",
  //       "haveRemark": false,
  //       "haveLetter": true
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:05.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:05.000+00:00",
  //       "workflowState": 10,
  //       "permissionRole": "RO",
  //       "externalStatusEng": "Processing",
  //       "externalStatusChi": "處理中",
  //       "externalStatusSchi": "处理中",
  //       "internalStatus": "Post-Approval (Pending Mail)",
  //       "internalAction": "Send",
  //       "haveRemark": false,
  //       "haveLetter": false
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:05.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:05.000+00:00",
  //       "workflowState": 11,
  //       "permissionRole": "VO",
  //       "externalStatusEng": "Processing",
  //       "externalStatusChi": "處理中",
  //       "externalStatusSchi": "处理中",
  //       "internalStatus": "Pending Rejection",
  //       "internalAction": "Proceed, Reprocess",
  //       "haveRemark": true,
  //       "haveLetter": false
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:05.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:05.000+00:00",
  //       "workflowState": 12,
  //       "permissionRole": "VS1",
  //       "externalStatusEng": "Processing",
  //       "externalStatusChi": "處理中",
  //       "externalStatusSchi": "处理中",
  //       "internalStatus": "Pending Rejection #1",
  //       "internalAction": "Proceed, Reprocess",
  //       "haveRemark": true,
  //       "haveLetter": false
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:05.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:05.000+00:00",
  //       "workflowState": 13,
  //       "permissionRole": "VS2",
  //       "externalStatusEng": "Processing",
  //       "externalStatusChi": "處理中",
  //       "externalStatusSchi": "处理中",
  //       "internalStatus": "Pending Rejection #2",
  //       "internalAction": "Proceed, Reprocess",
  //       "haveRemark": true,
  //       "haveLetter": false
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:05.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:05.000+00:00",
  //       "workflowState": 14,
  //       "permissionRole": "SO",
  //       "externalStatusEng": "Processing",
  //       "externalStatusChi": "處理中",
  //       "externalStatusSchi": "处理中",
  //       "internalStatus": "Pending Rejection #3",
  //       "internalAction": "Proceed, Reprocess",
  //       "haveRemark": true,
  //       "haveLetter": false
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:05.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:05.000+00:00",
  //       "workflowState": 15,
  //       "permissionRole": "PVO,VO",
  //       "externalStatusEng": "Processing",
  //       "externalStatusChi": "處理中",
  //       "externalStatusSchi": "处理中",
  //       "internalStatus": "Pending Rejection Letter",
  //       "internalAction": "Confirm",
  //       "haveRemark": false,
  //       "haveLetter": true
  //     },
  //     {
  //       "deleted": true,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:06.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:06.000+00:00",
  //       "workflowState": 16,
  //       "permissionRole": "VO",
  //       "externalStatusEng": "Processing",
  //       "externalStatusChi": "處理中",
  //       "externalStatusSchi": "处理中",
  //       "internalStatus": "Confirm Rejection Letter",
  //       "internalAction": "Queue",
  //       "haveRemark": false,
  //       "haveLetter": true
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:06.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:06.000+00:00",
  //       "workflowState": 17,
  //       "permissionRole": "PVO",
  //       "externalStatusEng": "Processing",
  //       "externalStatusChi": "處理中",
  //       "externalStatusSchi": "处理中",
  //       "internalStatus": "Rejected (Pending Mail)",
  //       "internalAction": "Send",
  //       "haveRemark": false,
  //       "haveLetter": false
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:06.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:06.000+00:00",
  //       "workflowState": 18,
  //       "permissionRole": "",
  //       "externalStatusEng": "Rejected",
  //       "externalStatusChi": "不獲批准",
  //       "externalStatusSchi": "不获批准",
  //       "internalStatus": "Rejected (Mailed Out)",
  //       "internalAction": "",
  //       "haveRemark": false,
  //       "haveLetter": false
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:06.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:06.000+00:00",
  //       "workflowState": 19,
  //       "permissionRole": "PP",
  //       "externalStatusEng": "Approved",
  //       "externalStatusChi": "已獲批准",
  //       "externalStatusSchi": "已获批准",
  //       "internalStatus": "Pending Payment",
  //       "internalAction": "Proceed",
  //       "haveRemark": true,
  //       "haveLetter": false
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:06.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:06.000+00:00",
  //       "workflowState": 20,
  //       "permissionRole": "VS1",
  //       "externalStatusEng": "Approved",
  //       "externalStatusChi": "已獲批准",
  //       "externalStatusSchi": "已获批准",
  //       "internalStatus": "Payment Approval #1",
  //       "internalAction": "Approve",
  //       "haveRemark": true,
  //       "haveLetter": false
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:06.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:06.000+00:00",
  //       "workflowState": 21,
  //       "permissionRole": "VS2",
  //       "externalStatusEng": "Approved",
  //       "externalStatusChi": "已獲批准",
  //       "externalStatusSchi": "已获批准",
  //       "internalStatus": "Payment Approval #2",
  //       "internalAction": "Approve",
  //       "haveRemark": true,
  //       "haveLetter": false
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:06.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:06.000+00:00",
  //       "workflowState": 22,
  //       "permissionRole": "PP",
  //       "externalStatusEng": "Approved",
  //       "externalStatusChi": "已獲批准",
  //       "externalStatusSchi": "已获批准",
  //       "internalStatus": "Payment Approved",
  //       "internalAction": "Confirm",
  //       "haveRemark": false,
  //       "haveLetter": false
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:06.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:06.000+00:00",
  //       "workflowState": 23,
  //       "permissionRole": "PP",
  //       "externalStatusEng": "Approved",
  //       "externalStatusChi": "已獲批准",
  //       "externalStatusSchi": "已获批准",
  //       "internalStatus": "Payment Confirmed",
  //       "internalAction": "",
  //       "haveRemark": false,
  //       "haveLetter": false
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:06.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:06.000+00:00",
  //       "workflowState": 24,
  //       "permissionRole": "RO",
  //       "externalStatusEng": "Querying",
  //       "externalStatusChi": "申請人須補交資料",
  //       "externalStatusSchi": "申请人须补交资料",
  //       "internalStatus": "1st Query (Mailed Out)",
  //       "internalAction": "Prepare",
  //       "haveRemark": false,
  //       "haveLetter": true
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:06.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:06.000+00:00",
  //       "workflowState": 25,
  //       "permissionRole": "RO",
  //       "externalStatusEng": "Querying",
  //       "externalStatusChi": "申請人須補交資料",
  //       "externalStatusSchi": "申请人须补交资料",
  //       "internalStatus": "1st Reminder (Pending Mail)",
  //       "internalAction": "Send",
  //       "haveRemark": false,
  //       "haveLetter": false
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:06.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:06.000+00:00",
  //       "workflowState": 26,
  //       "permissionRole": "RO",
  //       "externalStatusEng": "Querying",
  //       "externalStatusChi": "申請人須補交資料",
  //       "externalStatusSchi": "申请人须补交资料",
  //       "internalStatus": "1st Reminder (Mailed Out)",
  //       "internalAction": "Prepare",
  //       "haveRemark": false,
  //       "haveLetter": true
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:06.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:06.000+00:00",
  //       "workflowState": 27,
  //       "permissionRole": "RO",
  //       "externalStatusEng": "Querying",
  //       "externalStatusChi": "申請人須補交資料",
  //       "externalStatusSchi": "申请人须补交资料",
  //       "internalStatus": "2nd Reminder (Pending Mail)",
  //       "internalAction": "Send",
  //       "haveRemark": false,
  //       "haveLetter": false
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:06.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:06.000+00:00",
  //       "workflowState": 28,
  //       "permissionRole": "RO",
  //       "externalStatusEng": "Querying",
  //       "externalStatusChi": "申請人須補交資料",
  //       "externalStatusSchi": "申请人须补交资料",
  //       "internalStatus": "2nd Reminder (Mailed Out)",
  //       "internalAction": "Request Stop-processing",
  //       "haveRemark": true,
  //       "haveLetter": false
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:06.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:06.000+00:00",
  //       "workflowState": 29,
  //       "permissionRole": "VO",
  //       "externalStatusEng": "Querying",
  //       "externalStatusChi": "申請人須補交資料",
  //       "externalStatusSchi": "申请人须补交资料",
  //       "internalStatus": "Pending Stop-processing",
  //       "internalAction": "Confirm",
  //       "haveRemark": true,
  //       "haveLetter": false
  //     },
  //     {
  //       "deleted": true,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:06.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:06.000+00:00",
  //       "workflowState": 30,
  //       "permissionRole": "VO",
  //       "externalStatusEng": "Querying",
  //       "externalStatusChi": "申請人須補交資料",
  //       "externalStatusSchi": "申请人须补交资料",
  //       "internalStatus": "Confirm Stop-processing",
  //       "internalAction": "Prepare",
  //       "haveRemark": false,
  //       "haveLetter": true
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:06.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:06.000+00:00",
  //       "workflowState": 31,
  //       "permissionRole": "PVO",
  //       "externalStatusEng": "Querying",
  //       "externalStatusChi": "申請人須補交資料",
  //       "externalStatusSchi": "申请人须补交资料",
  //       "internalStatus": "Stop-processing (Pending Mail)",
  //       "internalAction": "Send",
  //       "haveRemark": false,
  //       "haveLetter": false
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": null,
  //       "createdOn": "2024-05-30T09:50:06.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:06.000+00:00",
  //       "workflowState": 32,
  //       "permissionRole": "",
  //       "externalStatusEng": "Stop-processing",
  //       "externalStatusChi": "無法處理",
  //       "externalStatusSchi": "无法处理",
  //       "internalStatus": "Confirmed Stop-processing (Pending Mail)",
  //       "internalAction": "",
  //       "haveRemark": false,
  //       "haveLetter": false
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": "System Init",
  //       "createdOn": "2024-05-30T09:50:06.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:06.000+00:00",
  //       "workflowState": 33,
  //       "permissionRole": "PVO",
  //       "externalStatusEng": "Processing",
  //       "externalStatusChi": "處理中",
  //       "externalStatusSchi": "处理中",
  //       "internalStatus": "Withdrawal (Pending Mail)",
  //       "internalAction": "Send",
  //       "haveRemark": false,
  //       "haveLetter": true
  //     },
  //     {
  //       "deleted": false,
  //       "createdBy": 0,
  //       "createdBySnap": "System Init",
  //       "createdOn": "2024-05-30T09:50:06.000+00:00",
  //       "modifiedBy": 0,
  //       "modifiedBySnap": "System Init",
  //       "modifiedOn": "2024-05-30T09:50:06.000+00:00",
  //       "workflowState": 34,
  //       "permissionRole": "",
  //       "externalStatusEng": "Application withdrawn",
  //       "externalStatusChi": "已取消申請",
  //       "externalStatusSchi": "已取消申请",
  //       "internalStatus": "Withdrawal (Mailed Out)",
  //       "internalAction": "",
  //       "haveRemark": false,
  //       "haveLetter": false
  //     }
  //   ],
  //   "message": "success"
  // }
}
